# Copyright (C) 2021, 2022, 2023  Dirk Stolle
#
# SPDX-License-Identifier: LGPL-3.0-or-later

FROM debian:12-slim
RUN apt-get update && \
    apt-get install -y bash git gcc libsqlite3-dev libssl-dev pkg-config \
                       nano mc wget && apt-get clean && \
    wget -O /tmp/ru.sh https://sh.rustup.rs && \
    chmod u+x /tmp/ru.sh
RUN /tmp/ru.sh -y --profile minimal --default-toolchain nightly
RUN export PATH="$HOME/.cargo/bin:$PATH"
RUN git clone https://github.com/striezel/corona.git /opt/corona
WORKDIR /opt/corona
RUN /root/.cargo/bin/cargo update --dry-run
CMD sleep 86400
